/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EasyWalksMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "creatorBalance"
      | "deactivateRoute"
      | "getRoute"
      | "hasPurchased"
      | "nextRouteId"
      | "owner"
      | "platformFeeBps"
      | "purchaseRoute"
      | "purchased"
      | "registerRoute"
      | "withdrawEarnings"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorPaid"
      | "EarningsWithdrawn"
      | "RoutePurchased"
      | "RouteRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "creatorBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRouteId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchased",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRoute",
    values: [AddressLike[], BigNumberish[], BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "creatorBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRoute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRouteId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchased", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace CreatorPaidEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoutePurchasedEvent {
  export type InputTuple = [
    routeId: BigNumberish,
    buyer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [routeId: bigint, buyer: string, price: bigint];
  export interface OutputObject {
    routeId: bigint;
    buyer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteRegisteredEvent {
  export type InputTuple = [
    routeId: BigNumberish,
    price: BigNumberish,
    creatorCount: BigNumberish
  ];
  export type OutputTuple = [
    routeId: bigint,
    price: bigint,
    creatorCount: bigint
  ];
  export interface OutputObject {
    routeId: bigint;
    price: bigint;
    creatorCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EasyWalksMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): EasyWalksMarketplace;
  waitForDeployment(): Promise<this>;

  interface: EasyWalksMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  creatorBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deactivateRoute: TypedContractMethod<
    [routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRoute: TypedContractMethod<
    [routeId: BigNumberish],
    [
      [string[], bigint[], bigint, string, boolean] & {
        creators: string[];
        sharesBps: bigint[];
        priceWei: bigint;
        routeHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [buyer: AddressLike, routeId: BigNumberish],
    [boolean],
    "view"
  >;

  nextRouteId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  purchaseRoute: TypedContractMethod<
    [routeId: BigNumberish],
    [void],
    "payable"
  >;

  purchased: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  registerRoute: TypedContractMethod<
    [
      creators: AddressLike[],
      sharesBps: BigNumberish[],
      priceWei: BigNumberish,
      routeHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  withdrawEarnings: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "creatorBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateRoute"
  ): TypedContractMethod<[routeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoute"
  ): TypedContractMethod<
    [routeId: BigNumberish],
    [
      [string[], bigint[], bigint, string, boolean] & {
        creators: string[];
        sharesBps: bigint[];
        priceWei: bigint;
        routeHash: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [buyer: AddressLike, routeId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextRouteId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseRoute"
  ): TypedContractMethod<[routeId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "purchased"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerRoute"
  ): TypedContractMethod<
    [
      creators: AddressLike[],
      sharesBps: BigNumberish[],
      priceWei: BigNumberish,
      routeHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreatorPaid"
  ): TypedContractEvent<
    CreatorPaidEvent.InputTuple,
    CreatorPaidEvent.OutputTuple,
    CreatorPaidEvent.OutputObject
  >;
  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RoutePurchased"
  ): TypedContractEvent<
    RoutePurchasedEvent.InputTuple,
    RoutePurchasedEvent.OutputTuple,
    RoutePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "RouteRegistered"
  ): TypedContractEvent<
    RouteRegisteredEvent.InputTuple,
    RouteRegisteredEvent.OutputTuple,
    RouteRegisteredEvent.OutputObject
  >;

  filters: {
    "CreatorPaid(address,uint256)": TypedContractEvent<
      CreatorPaidEvent.InputTuple,
      CreatorPaidEvent.OutputTuple,
      CreatorPaidEvent.OutputObject
    >;
    CreatorPaid: TypedContractEvent<
      CreatorPaidEvent.InputTuple,
      CreatorPaidEvent.OutputTuple,
      CreatorPaidEvent.OutputObject
    >;

    "EarningsWithdrawn(address,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "RoutePurchased(uint256,address,uint256)": TypedContractEvent<
      RoutePurchasedEvent.InputTuple,
      RoutePurchasedEvent.OutputTuple,
      RoutePurchasedEvent.OutputObject
    >;
    RoutePurchased: TypedContractEvent<
      RoutePurchasedEvent.InputTuple,
      RoutePurchasedEvent.OutputTuple,
      RoutePurchasedEvent.OutputObject
    >;

    "RouteRegistered(uint256,uint256,uint8)": TypedContractEvent<
      RouteRegisteredEvent.InputTuple,
      RouteRegisteredEvent.OutputTuple,
      RouteRegisteredEvent.OutputObject
    >;
    RouteRegistered: TypedContractEvent<
      RouteRegisteredEvent.InputTuple,
      RouteRegisteredEvent.OutputTuple,
      RouteRegisteredEvent.OutputObject
    >;
  };
}
